language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sachinarya/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sachinarya/docker-react npm run test